# Generated by Django 5.1.2 on 2024-10-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_categorymodel_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='Tasks',
        ),
    ]
