# Generated by Django 5.1.2 on 2024-10-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_title', models.CharField(max_length=50)),
                ('Task_discription', models.CharField(max_length=100)),
                ('Is_completed', models.BooleanField(default=False)),
                ('Task_assign_date', models.DateField()),
            ],
        ),
    ]
